Repository vanshchauhan21/CryptoTracker, pull requests merged in 2024-11, with the labels that each got.

#303 Added Real-time cryptocurrency Market Data
  src/App.js
  src/components/Footer.jsx
  src/pages/CryptoMarket.css
  src/pages/CryptoMarket.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#314 Enhance design of Back-to-Top button for improved user experience
  package-lock.json
  public/index.html
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#317 Implement Bitcoin Buy, Sell, and Hold Section #258
  public/Bit-Coin.jpg
  src/App.js
  src/components/Common/BuyBitCoin/BuyBitCoin.css
  src/components/Common/BuyBitCoin/BuyBitcoin.js
  src/components/Footer.jsx
  src/pages/BitCoinRainBow/BitcoinRainbowChart.css
  src/pages/BitCoinRainBow/BitcoinRainbowChart.js
  src/pages/Coin/Coin.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#318 Feature/add defi asset tracking 261
  src/App.js
  src/components/Footer.jsx
  src/pages/DefiAssets/DefiAssets.css
  src/pages/DefiAssets/DefiAssets.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#325 visitors count and star us button added in footer #319 done
  src/components/Footer.jsx
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#326 Add Profit/Loss Options in Portfolio for Crypto Tracker
  src/App.js
  src/components/Footer.jsx
  src/pages/ProfitLoss/ProfitLoss.css
  src/pages/ProfitLoss/ProfitLoss.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#327 added CryptoTracker logo in navbar
  public/index.html
  src/components/Common/Header/index.js
  src/components/Common/Header/styles.css
Labels: hacktoberfest-accepted, Wob24, level1, gssoc, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#320 improved compare page's UI/UX
  src/components/ComparePage/SelectCoins/index.js
  src/components/ComparePage/SelectCoins/styles.css
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#362 Add NFT Section to Crypto Tracker
  src/App.js
  src/components/Footer/Footer.css
  src/components/Footer/Footer.jsx
  src/pages/NFTShowcase/NFTShowcase.css
  src/pages/NFTShowcase/NFTShowcase.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#355 Added 24h crypto market page
  src/App.js
  src/components/Footer/Footer.jsx
  src/pages/CryptoMarket24h/CryptoMarket24h.css
  src/pages/CryptoMarket24h/CryptoMarket24h.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#354 Need only one either sign up or log in
  src/components/Common/Header/MobileMenuButton.css
  src/components/Common/Header/drawer.js
  src/components/Common/Header/index.js
  src/components/Common/Header/styles.css
Labels: hacktoberfest-accepted, Wob24, level1, gssoc, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#351 Enhance log in and log out page
  src/index.css
  src/pages/Login.js
  src/pages/Signup.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#353 Added Ethereum Rainbow Chart
  src/App.js
  src/components/Footer/Footer.jsx
  src/pages/EthereumRainbow/EthereumRainbowChart.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#350 Added learn more section on bitcoin rainbow chart Page
  src/pages/BitCoinRainBow/BitcoinRainbowChart.css
  src/pages/BitCoinRainBow/BitcoinRainbowChart.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#363 added animated learn more button
  src/components/Learn.css
  src/components/Learn.jsx
  src/components/learn-button/Learn-button.css
  src/components/learn-button/Learnmorebutton.jsx
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#373 Improve Navbar UI for Dark Mode Compatibility
  src/components/Common/Header/styles.css
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#372 Fix background color mismatch for GitHub and Visitor Count frames to match footer
  src/components/Footer/Footer.jsx
  src/index.css
Labels: hacktoberfest-accepted, Wob24, level1, gssoc, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#369 Our Vision section
  src/assets/logo-2.png
  src/components/Common/OurVision/OurVision.css
  src/components/Common/OurVision/OurVision.js
  src/components/LandingPage/MainComponent/index.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#364 integrated dark mode theme in crypto profit calculator
  src/pages/CryptoProfitCalculator.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#365 added animation in the watchlist page
  package-lock.json
  package.json
  src/assets/emptyanimation.json
  src/pages/Watchlist.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#367 added dark mode for the footer
  src/App.css
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#382 added social links to the footer of read me
  README.md
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#381 Add styles in contribute section
  src/components/Common/Contributors Card/ContributorCard.css
  src/pages/Contributors.css
  src/pages/Contributors.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#383 Add new page about How to Track NFTs on Crypto Tracker
  src/App.js
  src/components/Footer.jsx
  src/pages/Track NFT/TrackNFTs.css
  src/pages/Track NFT/TrackNFTs.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#387 Enhance dark mode style
  package-lock.json
  src/pages/CryptoConverter.css
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#386 Add new page about learn about crypto tracker reward
  src/App.js
  src/components/Footer.jsx
  src/pages/Cryptoreward/Cryptoreward.css
  src/pages/Cryptoreward/Cryptoreward.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#385 added:: Missing Meta Tags, robots.txt, sitemaps for SEO Enhancement
  generate-sitemap.js
  package-lock.json
  package.json
  public/robots.txt
  public/sitemap.xml
  src/App.js
  src/metadata.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#384 Add new page How to Buy Crypto with Card
  src/App.js
  src/components/Footer.jsx
  src/pages/CryptoCard/Cryptocard.css
  src/pages/CryptoCard/Cryptocard.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#378 added contact us page
  src/App.js
  src/components/Common/Header/index.js
  src/pages/Contactus/Contactus.jsx
  src/pages/Contactus/contactus.svg
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#389 Adding HOVER effect to the learn Section
  src/components/Learn.css
Labels: documentation, hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Status: Approved

#388 Content visibility in dark mode
  src/pages/ImpermanentLossCalculator.css
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#392 Update Signup.js
  src/pages/Signup.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#390 added send email functionality
  backend/.gitignore
  backend/controller/ContactController.js
  backend/package-lock.json
  backend/package.json
  backend/routes/contactroutes.js
  backend/server.js
  package-lock.json
  package.json
  src/pages/Contactus/Contactus.jsx
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#406 Update convertNumber.js
  src/functions/convertNumber.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#404 Update index.css
  src/index.css
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#407 Feature/add news trending links footer
  package-lock.json
  src/components/Footer.css
  src/components/Footer.jsx
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#393 Fetch data dynamically from gecko API in Bitcoin rainbow chart
  src/App.js
  src/components/Footer.jsx
  src/pages/BitCoinRainBow/BitcoinRainbowChart.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#401 Created new BTC Dominance chart
  src/App.js
  src/components/Footer.jsx
  src/pages/BTCDominance/BTCDominance.css
  src/pages/BTCDominance/BTCDominance.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#416 Create Separate Page for Crypto Tracker Rewards
  src/App.js
  src/components/Footer.jsx
  src/pages/Cryptoreward/Cryptoreward.css
  src/pages/Cryptoreward/Cryptoreward.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#413 Feature/add premium free trial option 336
  src/assets/Free-trial.jpg
  src/components/Common/FreeTrial/FreeTrial.css
  src/components/Common/FreeTrial/FreeTrial.js
  src/components/LandingPage/MainComponent/index.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#409 dark mode form color
  src/pages/Contactus/Contactus.jsx
Labels: hacktoberfest-accepted, Wob24, level1, gssoc, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#21 Update README.md
  README.md
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#419 Add MarketUpdate Page and MarketCard Component
  src/App.js
  src/components/Common/MarketCard/MarketCard.css
  src/components/Common/MarketCard/MarketCard.js
  src/components/Common/MarketCard/dfsdf
  src/components/Footer.jsx
  src/pages/MarketUpdate/MarketUpdate.css
  src/pages/MarketUpdate/MarketUpdate.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#420 added animation upon scroll in the home page
  package-lock.json
  package.json
  src/components/Common/FreeTrial/FreeTrial.js
  src/components/Common/Header/index.js
  src/components/Common/InDepthAnalysis/InDepthAnalysis.css
  src/components/Common/InDepthAnalysis/InDepthAnalysis.js
  src/components/Common/OurVision/OurVision.js
  src/components/LandingPage/MainComponent/index.js
  src/components/LandingPage/MainComponent/styles.css
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#418 ✅ Enhanced the Star US button
  src/components/Footer.jsx
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#421 Adjust content color for better visibility
  src/pages/TermCondition.css
Labels: hacktoberfest-accepted, Wob24, level1, gssoc, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#424 Challenging Implementation of Help Center Link in Footer: Navigating API and JSON Complexities
  package-lock.json
  src/App.js
  src/components/Common/MarketCard/dfsdf
  src/components/Footer.jsx
  src/pages/HelpCenter/HelpCenter.css
  src/pages/HelpCenter/HelpCenter.js
  src/pages/HelpCenter/HelpCenter.json
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#422 Added table of top 5 coins in dashboard
  src/components/Dashboard/TopCoinsTable/LineGraph.js
  src/components/Dashboard/TopCoinsTable/TopCoinsTable.js
  src/components/Dashboard/TopCoinsTable/styles.css
  src/pages/Dashboard.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#428 added newsletter subscrition email
  backend/controller/ContactController.js
  backend/controller/logo.png
  backend/routes/contactroutes.js
  backend/server.js
  src/components/Footer.jsx
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#423 Added crypto news page and backend route to fetch news from NEWS API
  backend/.env.example
  backend/package.json
  backend/server.js
  src/App.js
  src/components/Footer.jsx
  src/pages/CryptoNews/CryptoNews.css
  src/pages/CryptoNews/CryptoNews.js
Labels: Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#434 Fix Dark Mode Display Issues Across App, Footer, and Terms of Use Page
  src/App.js
  src/components/Footer.jsx
  src/pages/TermsOfUse.css
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#431 Feature/help center styling dark mode
  src/App.js
  src/pages/HelpCenter/HelpCenter.css
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#429 fixed navbar
  src/components/Common/Header/index.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#443 profeesubscription.js
  src/pages/Pro-Free-Subscribtion/ProFreeSubcription.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#442 Added a "How to Buy Crypto Card" Guide Page
  src/pages/CryptoCard/Cryptocard.css
  src/pages/CryptoCard/Cryptocard.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#440 Auto Redirect to Home Page on Invalid URL After 3 Seconds
  src/App.js
  src/components/Footer.jsx
  src/components/PageNotFound/PageNotFound.jsx
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#439 Fix Broken Link for DeFi Asset Section
  src/App.js
  src/pages/DefiAssets/DefiAssets.js
  src/pages/HelpCenter/HelpCenter.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#437 Added social media icons on faq page
  src/pages/Faq.css
  src/pages/Faq.js
Labels: hacktoberfest-accepted, Wob24, level1, gssoc, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#441 Added learn more section on impermanent loss calculator page
  src/pages/ImpermanentLossCalculator.css
  src/pages/ImpermanentLossCalculator.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#455 Add "Back to Top" Scroll-Up Button in README
  README.md
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#458 Feature/add blog separate route 427
  src/App.js
  src/components/Footer.jsx
  src/pages/Blogs/Blog.css
  src/pages/Blogs/Blog.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#460 Enhance/disclaimer page design dark mode 449
  src/components/Footer.jsx
  src/pages/Disclaimer/Disclaimer.css
  src/pages/Disclaimer/Disclaimer.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#464 Added crypto news page and route to fetch price from coinpaprika API
  src/App.js
  src/components/Footer.jsx
  src/pages/Dashboard.js
  src/pages/cryptoPrice/cryptPrice.css
  src/pages/cryptoPrice/cryptoPrice.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#475 Add nft market update route 466
  src/App.css
  src/App.js
  src/components/Common/MarketCard/MarketCard.css
  src/components/Common/MarketCard/MarketCard.js
  src/components/Footer.css
  src/components/Footer.jsx
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#479 corrected darkmode visibility
  src/pages/CryptoMarket24h/CryptoMarket24h.css
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#480 Added Bitcoin Rainbow Information Section
  src/components/BitcoinRainbowInfo.css
  src/components/BitcoinRainbowInfo.js
  src/pages/BitCoinRainBow/BitcoinRainbowChart.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#482 Fix/market alignment dark mode 467
  src/App.js
  src/pages/CryptoMarket24h/Crypto24HourReport.css
  src/pages/CryptoMarket24h/Crypto24HourReport.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#498 corrected Content visibility issue on Portfolio profit and loss overview
  src/pages/ProfitLoss/ProfitLoss.css
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#497 Removed duplicate footer from dashboard
  src/pages/Dashboard.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#484 Added Ethereum rainbow chart info section
  src/pages/EthereumRainbow/EthereumRainbowChart.js
  src/pages/EthereumRainbow/EthereumRainbowInfo.css
  src/pages/EthereumRainbow/EthereumRainbowInfo.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#500 Added Feedback section for all learn more pages
  src/components/Feedback/Feedbacksection.css
  src/components/Feedback/Feedbacksection.js
  src/pages/CryptoCard/Cryptocard.js
  src/pages/Cryptoreward/Cryptoreward.js
  src/pages/DefiAssets/DefiAssets.js
  src/pages/ProfitLoss/ProfitLoss.js
  src/pages/Track NFT/TrackNFTs.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#501 "Integrate CryptoNews Page and Layout Enhancements
  src/App.js
  src/components/Footer.jsx
  src/pages/CryptoNews/CryptoNews.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#430 Feature/whats trending page
  package-lock.json
  src/App.js
  src/components/Footer.jsx
  src/pages/WhatsTrending/WhatsTrending.css
  src/pages/WhatsTrending/WhatsTrending.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#496 Add new 'About Us' page for website
  src/App.js
  src/components/Footer.jsx
  src/pages/Aboutus/Aboutus.jsx
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#507 Added buy bitcoin section on bitcoin rainbow page
  src/assets/bitcoin.jpg
  src/components/BuyBitcoinSection/BuyBitcoinSection.css
  src/components/BuyBitcoinSection/BuyBitcoinSection.js
  src/pages/BitCoinRainBow/BitcoinRainbowChart.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#510 Fix/dark mode reward route display issue 487
  src/App.js
  src/components/Footer.jsx
  src/pages/Cryptoreward/Cryptoreward.css
  src/pages/Cryptoreward/Cryptoreward.js
  src/pages/Cryptoreward/cryptoRewardsData.json
Labels: hacktoberfest-accepted, Wob24, level1, gssoc, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#509 Added animation on scroll on contributor cards
  src/App.js
  src/components/ContributorAnimation/ContributorAnimation.css
  src/components/ContributorAnimation/ContributorAnimation.js
  src/components/ContributorAnimation/index.js
  src/pages/Contributors.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#514 "Add TrackNFTs Page with Light/Dark Mode Styling and Content Structure"
  src/App.js
  src/pages/TrackNFT/TrackNFTs.css
  src/pages/TrackNFT/TrackNFTs.js
Labels: hacktoberfest-accepted, Wob24, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#508 roadmap added on the learn page
  package-lock.json
  package.json
  src/components/Learn.jsx
  src/components/Roadmap.jsx
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#483 [Feature]: Implement Crypto News Card Layout for 24h Report
  src/pages/CryptoMarket24h/Crypto24HourReport.css
  src/pages/CryptoMarket24h/Crypto24HourReport.js
  src/pages/CryptoMarket24h/CryptoMarket24h.css
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#515 Corrected uneven alignment on pricing page
  src/App.js
  src/components/Common/Price Card/PriceCard.css
  src/pages/Pricing/Pricing.css
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#519 Added fear and greed index chart
  src/App.js
  src/components/Footer.jsx
  src/pages/FearAndGreedIndex/FearAndGreedIndex.css
  src/pages/FearAndGreedIndex/FearAndGreedIndex.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#520 Added table of top 5 NFTs on dashboard using coingecko API
  src/App.js
  src/components/Common/TopButton/index.js
  src/components/Dashboard/TopNftsTable/TopNftsTable.js
  src/components/Dashboard/TopNftsTable/styles.css
  src/pages/Cryptoreward/Cryptoreward.js
  src/pages/Dashboard.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#522 improved the email template
  backend/controller/ContactController.js
  backend/package-lock.json
  package-lock.json
  src/App.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#525 Feature/implement carousel card
  src/components/LandingPage/MainComponent/index.js
  src/components/LoveOurWebsite/LoveOurWebsiteCarousel.css
  src/components/LoveOurWebsite/LoveOurWebsiteCarousel.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#528 Added users feedback section on about us page
  package-lock.json
  package.json
  src/components/Testimonials/Testimonials.css
  src/components/Testimonials/Testimonials.js
  src/pages/Aboutus/Aboutus.jsx
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#554 Fix watchlist remove and add coin feature
  src/components/Dashboard/Grid/index.js
  src/functions/removeItemToWatchlist.js
  src/functions/saveItemToWatchlist.js
  src/pages/Watchlist.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#552 fix: 🐛 Revamp Gemini chat to work properly on user prompts
  .env
  package-lock.json
  package.json
  src/pages/GeminiAIChat/GeminiAIChat.jsx
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#549 Improve Track NFT Card Design and Add Animations
  src/App.js
  src/components/Footer.jsx
  src/pages/Track NFT/TrackNFTs.css
  src/pages/Track NFT/TrackNFTs.js
  src/pages/TrackNFT/TrackNFTs.css
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#550 ci: 🎡 remotion studio setup
  stargazers/.eslintrc
  stargazers/.gitignore
  stargazers/.prettierrc
  stargazers/package-lock.json
  stargazers/package.json
  stargazers/remotion.config.ts
  stargazers/src/Main.tsx
  stargazers/src/index.ts
  stargazers/src/utils.ts
  stargazers/tsconfig.json
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#541 Fix routing and improve UI for Bitcoin Rainbow Chart pages
  src/App.js
  src/components/BitcoinRainbowInfo.css
  src/components/BitcoinRainbowInfo.js
  src/pages/BitCoinRainBow/BitCoinRainBowCharDetail.css
  src/pages/BitCoinRainBow/BitCoinRainBowCharDetail.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#540 Blog Page does not exist and Info of it
  src/App.js
  src/components/Footer.jsx
Labels: Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#543 Enhance the navbar
  src/components/Common/Header/styles.css
Labels: hacktoberfest-accepted, Wob24, level1, gssoc, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#555 Improve Crypto Reward Page Structure and Styling
  package-lock.json
  src/App.js
  src/pages/Cryptoreward/Cryptoreward.css
  src/pages/Cryptoreward/Cryptoreward.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#556 Add Navbar, Footer, and Dark Mode Support to What’s Trending Route
  src/pages/WhatsTrending/WhatsTrending.js
Labels: hacktoberfest-accepted, Wob24, level1, gssoc, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#564 created responsive methodology page with attractive UI
  src/App.js
  src/components/Footer.jsx
  src/pages/Methodology/Methodology.css
  src/pages/Methodology/Methodology.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#562 Created sitemap
  src/App.js
  src/components/Footer.jsx
  src/pages/Sitemap/Sitemap.css
  src/pages/Sitemap/Sitemap.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#561 Improve Market Update Page: Grid Layout, Card Style Enhancement, and Animation Updates
  src/components/Common/MarketCard/MarketCard.css
  src/components/Common/MarketCard/MarketCard.js
  src/pages/MarketUpdate/MarketUpdate.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#560 Fix content visibility on Portfolio Profit and Loss page
  src/pages/ProfitLoss/ProfitLoss.css
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#571 Created responsive buy Ethereum section
  src/assets/ethereum-coin.png
  src/pages/EthereumRainbow/EthereumBuySection.css
  src/pages/EthereumRainbow/EthereumBuySection.js
  src/pages/EthereumRainbow/EthereumRainbowChart.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#578 feat: add LottieSpinner component for loading animation
  package-lock.json
  package.json
  src/components/Common/LottieSpinner/LottieSpinner.css
  src/components/Common/LottieSpinner/LottieSpinner.js
  src/components/Common/LottieSpinner/loading-spinner.json
  src/components/Common/MarketCard/MarketCard.js
  src/pages/MarketUpdate/MarketUpdate.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#585 Integrate Advanced Fear and Greed Indicator
  src/App.js
  src/components/CustomFearAndGreedIndicator.css
  src/components/CustomFearAndGreedIndicator.js
  src/pages/FearAndGreedIndex/FearAndGreedIndex.css
  src/pages/FearAndGreedIndex/FearAndGreedIndex.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#584 Enhance Privacy Policy Page Styling and Content for Consistency with Crypto Standards
  src/components/Common/Header/styles.css
  src/pages/Privacy-Policy/PrivacyPolicy.css
  src/pages/Privacy-Policy/PrivacyPolicy.js
Labels: hacktoberfest-accepted, Wob24, level1, gssoc, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#580 Add Click Handler for "Start My Free Trial" Button and Scroll-to-Top in Pricing Page
  src/components/Common/FreeTrial/FreeTrial.js
  src/pages/Pricing/Pricing.js
Labels: hacktoberfest-accepted, Wob24, level1, gssoc, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#587 Add AnalyzeAssets page with relevant content and layout
  src/assets/new-portfolio-banner-solana.svg
  src/components/Common/StarButton/StartButton.css
  src/components/Common/StarButton/StartButton.js
  src/components/LandingPage/MainComponent/index.js
  src/pages/AnalyzeAssets/AnalyzeAssets.css
  src/pages/AnalyzeAssets/AnalyzeAssets.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#601 Created responsive earn page
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/components/Common/Footer/footer.js
  src/components/Footer.jsx
  src/pages/Earn/Earn.css
  src/pages/Earn/Earn.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#609 perf: ⚡️ Enhance the UI and proper response return format
  src/pages/GeminiAIChat/GeminiAIChat.jsx
Labels: hacktoberfest-accepted, Wob24, level1, gssoc, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#616 fixed the navbar
  package-lock.json
  src/components/Common/Header/index.js
  src/components/Common/Header/styles.css
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#617 added animation
  src/components/Dashboard/Grid/index.js
  src/components/Dashboard/Tabs/index.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#613 Build responsive blog page
  src/App.js
  src/components/Footer.jsx
  src/components/Sidebar.css
  src/components/Sidebar.js
  src/pages/Blogs/Blog.css
  src/pages/Blogs/Blog.js
  src/pages/Blogs/BlogPost.css
  src/pages/Blogs/BlogPost.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#598 Added Compound Interest Calculator
  src/App.js
  src/components/Footer.jsx
  src/pages/CompoundInterestCalculator.css
  src/pages/CompoundInterestCalculator.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#627 added margin calculator
  package-lock.json
  src/App.js
  src/components/Footer.jsx
  src/pages/MarginCalculator.css
  src/pages/MarginCalculator.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#633 Fixed chatbot and scroll-to-top buttons alignments and made it responsive.
  public/index.html
  src/App.js
  src/components/BackToTopButton/BackToTopButton.css
  src/components/BackToTopButton/BackToTopButton.js
  src/components/Footer.jsx
  src/index.css
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#638 Created knowledge hub on profit return calculator
  src/pages/KnowledgeHub/KnowledgeHub.css
  src/pages/KnowledgeHub/KnowledgeHub.js
  src/pages/Useful Tools/ProfitReturnCalculator.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#634 Adding a new section to the main page of the website "Real-Time Market Data"
  src/components/LandingPage/MainComponent/index.js
  src/pages/Real-timeMarket-data/Marketdata.css
  src/pages/Real-timeMarket-data/Marketdata.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#639 stats added on about us page
  package-lock.json
  package.json
  src/pages/Aboutus/Aboutus.jsx
  src/pages/Aboutus/Stats.css
  src/pages/Aboutus/Stats.jsx
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#643 added contact animation in the conatct us page
  src/pages/Contactus/Contactus.jsx
  src/pages/Contactus/contact.css
  src/pages/Contactus/contact.json
Labels: hacktoberfest-accepted, Wob24, level1, gssoc, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#637 Adding an "Investment Return Calculator"
  src/App.js
  src/components/Footer.jsx
  src/pages/Useful Tools/Investmentreturncalculator.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#642 Remotion application componenets done
  stargazers/src/Content.tsx
  stargazers/src/cache.ts
  stargazers/src/gh-styles.css
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor

#640 fixed the text color for light mode
  src/components/Dashboard/Grid/index.js
  src/components/Dashboard/List/index.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#661 Enhanced defi assets styling
  package-lock.json
  src/App.js
  src/pages/DefiAssets/DeFiAssetStyles.css
  src/pages/DefiAssets/DefiAssets.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#645 added percent change calculator
  src/App.js
  src/components/Footer.jsx
  src/pages/PercentageChangeCalculator.css
  src/pages/PercentageChangeCalculator.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#666 Add New Crypto Tracking Features and Assets for Enhanced User Experience
  package-lock.json
  src/App.js
  src/assets/Bitcoin.png
  src/assets/Defi.png
  src/assets/Wallet.png
  src/components/CryptoTrackerManagingTool/CryptoTrackerManagingTool.css
  src/components/CryptoTrackerManagingTool/CryptoTrackerManagingTool.js
  src/components/LandingPage/MainComponent/index.js
Labels: Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#668 Implement Centered Lottie Spinner in Contributors Page
  src/pages/Contributors.css
  src/pages/Contributors.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor

#667 Adding remember checkbox and forgot password to the login page
  package-lock.json
  package.json
  src/App.js
  src/pages/Login.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#672 Strengthen User Trust with "Fortified Security for Your Digital Assets" on Crypto Profit
  package-lock.json
  src/components/SecuritySection/SecuritySection.css
  src/components/SecuritySection/SecuritySection.js
  src/pages/CryptoProfitCalculator.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#705 Fix content visibility issues on DeFi Asset Tracking page
  src/pages/DefiAssets/DeFiAssetStyles.css
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#565 Created responsive affiliate program page
  src/App.js
  src/components/Footer.jsx
  src/pages/AffiliateProgram/AffiliateProgram.css
  src/pages/AffiliateProgram/AffiliateProgram.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#706 Enhance styling of Fear and Greed Index page for better user experience
  src/components/LoveOurWebsite/LoveOurWebsiteCarousel.css
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#683 fixing light and dark mode appearance in multiple pages
  src/components/Common/Price Card/PriceCard.css
  src/components/Dashboard/Grid/index.js
  src/components/Dashboard/Grid/styles.css
  src/pages/Contactus/Contactus.jsx
  src/pages/Pricing/Pricing.css
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#686 Developed and Integrated Ultimate Crypto Portfolio Tracker Page
  src/App.js
  src/components/Footer.jsx
  src/components/PortfolioChart.js
  src/components/PortfolioSummary.js
  src/pages/UltimateCryptoPortfolioTracker/UltimateCryptoPortfolioTracker.css
  src/pages/UltimateCryptoPortfolioTracker/UltimateCryptoPortfolioTracker.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#684 Developed an Essential, Feature-Rich Information Hub for CryptoProfit Calculator
  src/components/CryptoProfitCalculatorInfo.css
  src/components/CryptoProfitCalculatorInfo.js
  src/pages/CryptoProfitCalculator.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#680 Created knowledge center
  src/pages/CryptoKnowledgeBase/CryptoKnowledgeBase.css
  src/pages/CryptoKnowledgeBase/CryptoKnowledgeBase.js
  src/pages/MarginCalculator.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#682 Incorporate a 'Master the Math' Section for the Compound Interest Calculator
  src/pages/CompoundInterestCalculator.js
  src/pages/CompoundInterestCalculator/MasterTheMath.css
  src/pages/CompoundInterestCalculator/MasterTheMath.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#681 Implement Swap With Best Rates Component
  src/components/LandingPage/MainComponent/index.js
  src/components/SwapWithBestRates/SwapWithBestRates.css
  src/components/SwapWithBestRates/SwapWithBestRates.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#677 Added PortfolioComparison component for portfolio vs market section
  src/components/LandingPage/MainComponent/index.js
  src/pages/AnalyzeAssets/PortfolioComparison.css
  src/pages/AnalyzeAssets/PortfolioComparison.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#676 Adding Compound Interest Calculator for Crypto Staking to the website
  src/App.js
  src/components/Footer.jsx
  src/pages/cics.css
  src/pages/cics.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#671 Implement Dynamic Loading Indicator for Asynchronous Rendering on the Bitcoin Rainbow Chart Interface
  src/components/BuyBitcoinSection/BuyBitcoinSection.css
  src/pages/BitCoinRainBow/BitcoinRainbowChart.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#673 Adding a Crypto to Fiat Converter - Converts cryptocurrency to a fiat currency (USD, EUR, etc.) based on current market prices.
  src/App.js
  src/components/Footer.jsx
  src/pages/Cryptofiat.css
  src/pages/Cryptofiat.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#709 Fix catastrophic content visibility on Price page
  src/components/BuyBitcoinSection/BuyBitcoinSection.css
  src/components/Common/Price Card/PriceCard.css
  src/pages/EthereumRainbow/EthereumBuySection.css
  src/pages/Pricing/Pricing.css
  src/pages/Pricing/Pricing.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#710 Supercharge User Engagement with an 'Expert Insights & Pro Tips' Section for the Investment Return Calculator
  src/App.js
  src/pages/Useful Tools/Investmentreturncalculator.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#715 Added info section
  src/App.js
  src/pages/PercentageChangeCalculator.css
  src/pages/PercentageChangeCalculator.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#716 launched affiliate program
  src/pages/AffiliateProgram/AffiliateProgram.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#745 Implement Added Dynamic "Did This Answer Your Question?" Feedback and Comprehensive "Learn More About Impermanent Loss Calculator" Section
  src/pages/ImpermanentLossCalculator.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#742 Enhance d User Interaction with a Streamlined "Show More" Button for the Contributors Page
  src/pages/Contributors.css
  src/pages/Contributors.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#746 Integrate Platform Statistics Component for Crypto Management Overview
  src/components/LandingPage/MainComponent/index.js
  src/components/PlatformStatistics/PlatformStatistics.css
  src/components/PlatformStatistics/PlatformStatistics.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#741 Revamp Cookie Policy page UI for improved clarity and user engagement
  src/App.js
  src/pages/CompoundInterestCalculator.css
  src/pages/Cookie-Policy/CookiePolicy.css
  src/pages/Cookie-Policy/CookiePolicy.js
  src/pages/CryptoCard/Cryptocard.css
  src/pages/CryptoProfitCalculator.css
  src/pages/Dashboard.js
  src/pages/DividendCalculator.css
  src/pages/MarginCalculator.css
  src/pages/Refund Policy/RefundPolicy.css
  src/pages/cics.css
Labels: hacktoberfest-accepted, help wanted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#733 Added feedbacksection on faq page
  src/pages/Faq.js
Labels: hacktoberfest-accepted, Wob24, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#749 Enhance Disclaimer Page UI for improved accessibility and clarity
  src/pages/Disclaimer/Disclaimer.css
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#750 Added Feedback
  src/pages/BitCoinRainBow/BitcoinRainbowChart.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved
