Repository vanshchauhan21/CryptoTracker, pull requests merged in 2024-10, with the labels that each got.

#30 Adjust toggle, table for dark theme
  src/components/CoinPage/SelectDays/index.js
  src/components/CoinPage/SelectDays/styles.css
  src/components/CoinPage/ToggleComponent/index.js
Labels: GSSOC24

#38 Anchor tag for logo
  src/components/Common/Header/drawer.js
  src/components/Common/Header/index.js
Labels: gssoc-ext

#34 Enhance Navbar | Issue #13
  package-lock.json
  package.json
  src/components/Common/Header/index.js
  src/components/Common/Header/styles.css
Labels: Level 2, gssoc-ext

#41 Create LICENSE
  LICENSE
Labels: Level 2, gssoc-ext

#55 contributing.md file added
  Contributing.md
Labels: enhancement, level1, hacktoberfest-accepted, gssoc-ext

#85 Corrected duplicate footer
  src/App.js
  src/pages/Dashboard.js
Labels: enhancement, level3, hacktoberfest-accepted, gssoc-ext

#94 Feature Request: Add Authentication Using Google/GitHub etc
  .env.sample
  package-lock.json
  package.json
  src/components/Common/Header/index.js
  src/index.js
  src/pages/Login.js
  src/pages/Signup.js
Labels: level3, hacktoberfest-accepted, gssoc-ext

#105 enhanced footer section done
  src/App.css
  src/components/Footer.jsx
Labels: enhancement, level2, hacktoberfest-accepted, gssoc-ext

#138 feature/added multi language support button
  src/App.js
  src/components/Common/Header/index.js
  src/components/Common/Language Swicher/LanguageSwitcher.css
  src/components/Common/Language Swicher/LanguageSwitcher.js
  src/components/Footer.jsx
  src/components/LandingPage/MainComponent/index.js
  src/i18n.js
  src/locales/en.json
  src/locales/es.json
  src/locales/zh.json
Labels: hacktoberfest-accepted, Wob24, level3, hacktoberfest, gssoc-ext

#137 Remove duplicate footer
  src/pages/Dashboard.js
Labels: hacktoberfest-accepted, Wob24, level3, hacktoberfest, gssoc-ext

#141 Add Home Icon on Login and Sign-Up Pages
  package-lock.json
  package.json
  src/pages/Login.js
  src/pages/Signup.js
Labels: hacktoberfest-accepted, Wob24, level3, hacktoberfest, gssoc-ext

#145 Add Contributors Card Component and Multi-language Support
  src/App.css
  src/App.js
  src/components/Common/Contributors Card/ContributorCard.css
  src/components/Common/Contributors Card/ContributorCard.js
  src/components/Footer.jsx
  src/locales/en.json
  src/locales/es.json
  src/locales/zh.json
  src/pages/Contributors.js
  src/pages/Dashboard.js
Labels: hacktoberfest-accepted, Wob24, level3, hacktoberfest, gssoc-ext

#147 change footer gradient
  src/components/Common/Footer/styles.css
Labels: hacktoberfest-accepted, Wob24, level3, hacktoberfest, gssoc-ext

#158 fixed list glitch and added background color
  src/components/Dashboard/List/styles.css
Labels: hacktoberfest-accepted, Wob24, level2, hacktoberfest, gssoc-ext

#149 Resolved shadow overlapping
  src/components/Common/Footer/styles.css
  src/components/LandingPage/MainComponent/index.js
  src/components/LandingPage/MainComponent/styles.css
Labels: hacktoberfest-accepted, Wob24, level3, hacktoberfest, gssoc-ext

#165 update grid list color
  src/components/Dashboard/Tabs/index.js
  src/components/Dashboard/Tabs/styles.css
  src/components/LandingPage/MainComponent/styles.css
Labels: hacktoberfest-accepted, Wob24, level3, hacktoberfest, gssoc-ext

#170 Enhance: Privacy Policy Page Design and Content
  src/App.js
  src/components/LandingPage/MainComponent/styles.css
  src/pages/Home.js
  src/pages/Privacy-Policy/PrivacyPolicy.css
  src/pages/Privacy-Policy/PrivacyPolicy.js
  src/pages/PrivacyPolicy.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext

#180 Redesign Contributor Card to Align with Project Theme
  src/components/Common/Contributors Card/ContributorCard.css
  src/pages/Contributors.css
  src/pages/Contributors.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext

#174 Add spacing between navbar and search box on dashboard
  src/components/Dashboard/Search/styles.css
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext

#189 Adjusted color of pricing cards
  src/components/Common/Price Card/PriceCard.css
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext

#187 Added contributor's page
  src/pages/Contributors.css
  src/pages/Contributors.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext

#204 Multi-Language Support Using Language Translator
  src/App.js
  src/components/Footer.jsx
  src/components/GoogleTranslate.jsx
  src/pages/Contributors.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext

#207 Improved darkmode on privacypolicy page
  src/pages/Privacy-Policy/PrivacyPolicy.css
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext

#206 Added darkmode on learn page
  src/components/Learn.css
  src/components/Learn.jsx
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext

#223 added more readings and links for learn cryptocurrency page
  src/components/Learn.jsx
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext

#217 Revert "added currency convertor"
  src/components/InputBox.jsx
  src/components/LandingPage/MainComponent/CurrencyConvertor.jsx
  src/components/LandingPage/MainComponent/index.js
  src/components/index.js
  src/hooks/useCurrencyInfo.js
  src/pages/Learn.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, gssoc-ext

#216 fixed blue underlines in dashboard card's text
  src/pages/Privacy-Policy/PrivacyPolicy.css
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, gssoc-ext

#213 Add Cookies Policy page for Crypto Tracker
  src/App.js
  src/components/Footer.jsx
  src/pages/CookiesPolicy.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext

#228 Add Question and guideline section
  .github/ISSUE_TEMPLATE/config.yml
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext

#237 Added Crypto Converter
  src/App.js
  src/components/Footer.jsx
  src/pages/CryptoConverter.css
  src/pages/CryptoConverter.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext

#234 feat: Add Separate Routes for Pro and Free Subscriptions
  src/components/Common/Price Card/PriceCard.css
  src/components/Common/Price Card/PriceCard.js
  src/components/LandingPage/MainComponent/index.js
  src/pages/Pricing/Pricing.js
  src/pages/Pro-Free-Subscribtion/ProFreeSubcription.css
  src/pages/Pro-Free-Subscribtion/ProFreeSubcription.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext

#243 Add the PULL REQUEST TEMPLATE
  .github/PULL_REQUEST_TEMPLATE.md
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext

#241 added dark mode support for pricing section
  src/pages/Pricing/Pricing.css
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext

#251 fixed pricing appearing on home page
  src/components/LandingPage/MainComponent/index.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext

#245 Added mobile menu functionality to Header component
  src/components/Common/Header/MobileMenuButton.css
  src/components/Common/Header/MobileMenuButton.js
  src/components/Common/Header/index.js
  src/components/Common/Header/styles.css
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext

#244 fixed our contrinutors page and improved its UI and animation
  src/components/Common/Contributors Card/ContributorCard.css
  src/pages/Contributors.css
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext

#238 added more QnA in FAQs to improve user experience
  src/pages/Faq.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext

#231 fixed text not visible in dark mode
  src/index.css
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext

#78 Added Table to Display Repository Statistics in README.md
  README.md
Labels: hacktoberfest-accepted, gssoc, level2, hacktoberfest, gssoc-ext

#255 Enhance Feedback Form UI and Add Navbar
  src/pages/Feedback.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext

#256 📝[DOCS] adding Contributors section to readme.md
  README.md
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext

#265 Updated Terms and Conditions page styling for dark mode
  src/App.css
  src/pages/TermCondition.css
  src/pages/TermCondition.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext

#262 Added Bitcoin Rainbow Chart
  src/App.js
  src/components/Footer.jsx
  src/pages/BitcoinRainbowChart.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext

#273 fixed clerk authenticator default URL problem
  src/pages/Login.js
  src/pages/Signup.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext

#282 Added Crypto Profit Calculator
  src/App.js
  src/components/Footer.jsx
  src/pages/CryptoProfitCalculator.css
  src/pages/CryptoProfitCalculator.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#281 Add Impermanent Loss Calculator Page to Improve User Access and Functionality
  src/App.js
  src/components/Footer.jsx
  src/pages/Useful Tools/ImpermanentLossCalculator.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#285 fixed newsletter misalignment
  src/App.css
  src/components/Footer.jsx
  src/components/GoogleTranslate.jsx
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#280 Stargazers and Forkers section to readme.md
  README.md
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#279 fixed marquee contents links and appearance
  src/pages/Marquee/Marquee.css
Labels: hacktoberfest-accepted, help wanted, Wob24, gssoc, level3, hacktoberfest, Contributor, Status: Approved

#277 corrected feedback form title color
  src/pages/Feedback.css
  src/pages/Feedback.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#288 Enhance Contrast for Crypto Converter in Dark Mode
  src/pages/CryptoConverter.css
Labels: bug, hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#287 "Updated styles for Google Translate component"
  src/components/GoogleTranslate.jsx
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#290 Added Impermanent Loss Calculator
  src/App.js
  src/components/Footer.jsx
  src/pages/ImpermanentLossCalculator.css
  src/pages/ImpermanentLossCalculator.js
  src/pages/Useful Tools/ImpermanentLossCalculator.js
Labels: hacktoberfest-accepted, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#289 improve Profit Return Calculator input visibility in dark mode
  src/pages/Useful Tools/ProfitReturnCalculator.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#292 Added Crypto Profit calculator
  src/pages/CryptoProfitCalculator.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#294 Corrected logo shadow in footer
  src/pages/Marquee/Marquee.css
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#296 Remove duplicate text from useful tools in footer
  src/components/Footer.jsx
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#297 Fixed Footer Responsiveness
  src/App.css
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#298 added Buy Crypto with Card Compo
  src/pages/BuyCryptoByCard/CardPurchaseLanding .js
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#302 added back to top button
  package-lock.json
  package.json
  public/index.html
Labels: hacktoberfest-accepted, Wob24, gssoc, level2, hacktoberfest, gssoc-ext, Contributor, Status: Approved

#308 Added learn more section on cryptoconverter page
  src/pages/CryptoConverter.css
  src/pages/CryptoConverter.js
Labels: hacktoberfest-accepted, Wob24, gssoc, level3, hacktoberfest, gssoc-ext, Contributor, Status: Approved
