Repository vanshchauhan21/CryptoTracker, pull requests merged in 2025-01, with the labels that each got.

#810 Integrate Chatbot named "HashTrack" for Real-Time Cryptocurrency Information and Support
  public/index.html
  src/App.js
  src/components/Footer.jsx
  src/index.css
Labels: level2, Contributor, Status: Approved, SWOC

#812 Update navbar with new changes
  package-lock.json
  src/App.js
  src/components/Common/Header/index.js
  src/components/Common/Header/styles.css
  src/components/Footer.jsx
Labels: level1, Contributor, Status: Approved, SWOC

#814 fixed issue #813
  package-lock.json
  src/App.js
  src/components/Common/Header/index.js
  src/components/Common/Header/styles.css
  src/components/Footer.jsx
Labels: Contributor, Status: Approved, SWOC

#821 #815: Fix heading color in dark mode
  src/pages/TrackNFT/TrackNFTs.css
Labels: Contributor, Status: Approved, SWOC

#825 Fix Header Alignment and Responsiveness in CryptoTrackerAdd files via upload
  index.html
  styles.css
Labels: Contributor, Status: Approved, SWOC

#828 moved the div downward
  src/pages/Compare.js
Labels: IWOC2025, Medium
