Repository vanshchauhan21/CryptoTracker, pull requests merged in 2025-03, with the labels that each got.

#843 Create style.css
  style.css
Labels: Easy, Apertre2.0

#845 Footer Updated✅
  index.html
  package-lock.json
  src/App.js
  src/components/Footer.css
  src/components/Footer.jsx
  src/index.css
  styles.css
Labels: Medium, Apertre2.0

#851 Resolve✅
  package-lock.json
  src/components/PlatformStatistics/PlatformStatistics.css
Labels: Easy, Apertre2.0

#854 Footer Fixed✅
  src/components/Footer.jsx
Labels: Easy, Apertre2.0

#856 Added visibility for sidebar in dark mode
  src/components/Common/Header/drawer.js
  src/components/Common/Header/styles.css
Labels: Easy, Apertre2.0

#860 Fixed Tailwind Dark Mode & Theme-Based Text Color Sync
  src/components/Common/Header/index.js
  src/components/Common/Header/styles.css
  src/components/CryptoTrackerManagingTool/CryptoTrackerManagingTool.css
  src/components/CryptoTrackerManagingTool/CryptoTrackerManagingTool.js
  src/components/LandingPage/MainComponent/index.js
  src/components/PlatformStatistics/PlatformStatistics.css
  src/components/PlatformStatistics/PlatformStatistics.js
  src/index.css
  src/pages/Marquee/Marquee.css
  src/pages/Marquee/Marquee.js
  tailwind.config.js
Labels: Easy, Apertre2.0

#861 error hnadling
  src/App.js
Labels: Hard, Apertre2.0
