Repository vanshchauhan21/CryptoTracker, pull requests merged in 2025-02, with the labels that each got.

#829 Fixes #822
  .env
  .vscode/settings.json
  src/App.js
  src/pages/GeminiAIChat/GeminiAIChat.jsx
Labels: IWOC2025, Medium

#830 make all the button function
  src/App.js
Labels: IWOC2025, Easy

#834 make hampburger visible
  src/components/Common/Header/styles.css
Labels: IWOC2025, Easy

#835 Auth controllers added with JWT and mongodb implementation
  backend/.env.example
  backend/controller/auth.controllers.js
  backend/lib/db.js
  backend/models/user.model.js
  backend/package-lock.json
  backend/package.json
  backend/routes/auth.route.js
  backend/server.js
Labels: IWOC2025, Hard

#837 aligned the line between list components
  src/components/Dashboard/List/index.js
  src/components/Dashboard/List/styles.css
  src/pages/CryptoMarket24h/Crypto24HourReport.css
Labels: IWOC2025
