Repository vanshchauhan21/CryptoTracker, pull requests merged in 2025-04, with the labels that each got.

#864 Compare page redesign
  package-lock.json
  package.json
  src/components/CoinPage/Info/index.js
  src/components/CoinPage/Info/styles.css
  src/components/CoinPage/LineChart/index.js
  src/components/CoinPage/SelectDays/index.js
  src/components/CoinPage/SelectDays/styles.css
  src/components/CoinPage/ToggleComponent/index.js
  src/components/ComparePage/Chart.js
  src/components/ComparePage/ChartTab/Tabs.css
  src/components/ComparePage/ChartTab/Tabs.js
  src/components/ComparePage/SelectCoins/index.js
  src/components/ComparePage/SelectCoins/styles.css
  src/components/ComparePage/SelectDays/index.js
  src/components/ComparePage/SelectDays/styles.css
  src/components/Dashboard/List/index.js
  src/components/Dashboard/List/styles.css
  src/functions/get100Coins.js
  src/functions/getCoinData.js
  src/functions/getDate.js
  src/functions/settingChartData.js
  src/pages/Compare.js
Labels: Medium, Apertre2.0

#865 Main page
  index.html
  src/components/Common/FreeTrial/FreeTrial.css
  src/components/Common/FreeTrial/FreeTrial.js
  src/components/Common/InDepthAnalysis/InDepthAnalysis.css
  src/components/Common/InDepthAnalysis/InDepthAnalysis.js
  src/components/CryptoTrackerManagingTool/CryptoTrackerManagingTool.css
  src/components/ExitStrategy/ExitStrategy.css
  src/components/ExitStrategy/ExitStrategy.js
  src/components/LandingPage/MainComponent/index.js
  src/components/LoveOurWebsite/LoveOurWebsiteCarousel.css
  src/components/PlatformStatistics/PlatformStatistics.css
  src/components/PlatformStatistics/PlatformStatistics.js
  src/components/SwapWithBestRates/SwapWithBestRates.css
  src/components/UltimateSecurity/UltimateSecurity.js
  src/index.css
  src/pages/AnalyzeAssets/AnalyzeAssets.css
  src/pages/AnalyzeAssets/PortfolioComparison.css
  src/pages/Real-timeMarket-data/Marketdata.css
Labels: Medium, Apertre2.0

#868 overlapping issue
  src/components/Dashboard/Grid/styles.css
  src/components/Dashboard/List/index.js
  src/components/Dashboard/List/styles.css
  src/functions/settingChartData.js
  src/pages/Compare.js
Labels: Easy, Apertre2.0

#870 Responsive UI Fix for Compare Page (Laptop View)
  package-lock.json
  package.json
  src/components/CoinPage/Info/index.js
  src/components/CoinPage/ToggleComponent/index.js
  src/components/ComparePage/Chart.js
  src/components/ComparePage/SelectCoins/styles.css
  src/components/ComparePage/SelectDays/styles.css
  src/components/Dashboard/List/index.js
  src/pages/Compare.css
  src/pages/Compare.js
Labels: Easy, Apertre2.0

#876 Update file
  Contributing.md
Labels: Medium, Apertre2.0

#877 Update
  CODE_OF_CONDUCT.md
  LICENSE
Labels: Medium, Apertre2.0

#878 added chatbot
  public/index.html
Labels: Hard, Apertre2.0

#879 updated css styles
  style.css
Labels: Medium, Apertre2.0

#880 Update the chatbot and add more functionality
  Contributing.md
  index.html
  src/components/GoogleTranslate.jsx
  style.css
Labels: Hard, Apertre2.0

#881 update footer section
  index.html
  style.css
  styles.css
Labels: Medium, Apertre2.0

#882 Update
  index.html
  src/components/CalculatorProfit.jsx
  src/components/News.jsx
  style.css
Labels: Hard, Apertre2.0

#883 update styling
  index.html
  src/components/News.jsx
  style.css
Labels: Easy, Apertre2.0

#886 Update footer section
  src/App.css
  style.css
Labels: Easy, Apertre2.0

#885 added more styles
  src/App.css
  style.css
Labels: Easy, Apertre2.0

#889 Added new features in feedback form for the better response
  src/components/Feedback/Feedbacksection.js
Labels: Hard, Apertre2.0
